In the context of deep learning, we also use some less conventional notation. We
allow the addition of matrix and a vector, yielding another matrix: C = A+b, where
Ci;j = Ai;j + bj. In other words, the vector b is added to each row of the matrix.
This shorthand eliminates the need to define a matrix with b copied into each row
before doing the addition. This implicit copying of b to many locations is called
broadcasting.

### This Tutorial Covers 
#### 1.1 Scalar and One-Dimensional Array
#### 1.2 Scalar and Two-Dimensional Array
#### 1.3 One-Dimensional and Two-Dimensional Arrays
#### 1.4 Limitations of Broadcasting

## Surprise !!

In [5]:
a = [1, 2, 3]
b = [1, 2, 3]
c = a + b
c

[1, 2, 3, 1, 2, 3]

In [3]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([1, 2, 3])
c = a + b
c

array([2, 4, 6])

### 1.1 Scalar and One-Dimensional Array

In [4]:
a = np.array([1, 2, 3])
b=2
c=a+b
c

array([3, 4, 5])

### 1.2 Scalar and Two-Dimensional Array

In [6]:
a = np.array([[1, 2, 3],[3,4,5]])
b=2
c=a+b
c

array([[3, 4, 5],
       [5, 6, 7]])

### 1.3 One-Dimensional and Two-Dimensional Arrays

In [7]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([6,7,8])
c=a+b
c

array([[ 7,  9, 11],
       [10, 12, 14]])

### 1.4 Limitations of Broadcasting

In [9]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([5,6])
c=a+b

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 