### This tutorial is divided into 4 parts; they are:
#### 1. From List to Arrays
#### 2. Array Indexing
#### 3. Array Slicing
#### 4. Array Reshaping

#### 1. From List to Arrays

In [48]:
from numpy import array

data=[11,22,33,44,55]
data=array(data)
print(data)
print(type(data))

[11 22 33 44 55]
<class 'numpy.ndarray'>


In [49]:
from numpy import array

data=[[11,22],[33,44],[55,66]]
data=array(data)
print(data)
print(type(data))

[[11 22]
 [33 44]
 [55 66]]
<class 'numpy.ndarray'>


### 2. Array Indexing

#### a. One Dimensional Indexing
#### b. Two Dimensional Indexing

#### a. One Dimensional Indexing

In [50]:
from numpy import array

data=[11,22,33,44,55]
data=array(data)
print(data[0])
print(data[4])


11
55


In [51]:
print(data[-1])

55


In [52]:
print(data[-2])

44


In [53]:
print(data[-5])

11


#### b. Two Dimensional Indexing

In [54]:
from numpy import array

data=[[11,22],[33,44],[55,66]]
data=array(data)
print(data)
print(type(data))

[[11 22]
 [33 44]
 [55 66]]
<class 'numpy.ndarray'>


In [55]:
data[0,0]

11

In [56]:
data[0][0]

11

In [57]:
#If we are interested in all items in the first row,
#we could leave the second dimension index empty, 
data[0,]

array([11, 22])

#### 3. Array Slicing

#### a. One Dimensional Slicing
#### b. Two Dimensional Slicing

#### a. One Dimensional Slicing

In [58]:
from numpy import array

data=[11,22,33,44,55]
data=array(data)
data[:]


array([11, 22, 33, 44, 55])

In [59]:
data[0:1]

array([11])

In [60]:
data[-2:]

array([44, 55])

#### b. Two Dimensional Slicing

In [61]:
from numpy import array
#Split Input and Output Features
data=[[11,22,33],[44,55,66],[77,88,99]]
data=array(data)

In [62]:
X,y=data[:,:-1],data[:,-1]

In [63]:
X

array([[11, 22],
       [44, 55],
       [77, 88]])

In [64]:
y

array([33, 66, 99])

In [65]:
# split train and test data
from numpy import array
# define array
data = array([
[11, 22, 33],
[44, 55, 66],
[77, 88, 99]])
# separate data
split=2
train,test=data[:split,:],data[split:,:]

print(train)
print()
print(test)

[[11 22 33]
 [44 55 66]]

[[77 88 99]]


#### 4. Array Reshaping
#### (a). Reshape 1D to 2D Array
#### (b). Reshape 2D to 3D Array

In [66]:
from numpy import array

data=array([11,22,33,44,55])
print(data.shape)

(5,)


In [67]:
from numpy import array

data = array([
[11, 22, 33],
[44, 55, 66],
[77, 88, 99]])

data.shape

(3, 3)

#### (a). Reshape 1D to 2D Array

In [68]:
from numpy import array

data=array([11,22,33,44,55])
print(data)
print(data.shape)
print()
data=data.reshape((data.shape[0],1))
print(data)
data.shape

[11 22 33 44 55]
(5,)

[[11]
 [22]
 [33]
 [44]
 [55]]


(5, 1)

#### (b). Reshape 2D to 3D Array

In [69]:
data=array([[11,22],[33,44],[55,66]])

In [70]:
data=data.reshape((data.shape[0],2,1))
print(data)
data.shape

[[[11]
  [22]]

 [[33]
  [44]]

 [[55]
  [66]]]


(3, 2, 1)