###  Tutorial Content
### 1. What is a Matrix
### 2. Defining a Matrix
### 3. Matrix Arithmetic
### 4. Matrix-Matrix Multiplication
### 5. Matrix-Vector Multiplication
### 6. Matrix-Scalar Multiplication

### 1. What is a Matrix

A matrix is a two-dimensional array of scalars with one or more columns and one or more rows.

### 2. Defining a Matrix

In [3]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

### 3. Matrix Arithmetic

#### 3.1 Matrix Addition

In [5]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[5,6,7],[8,9,10]])
c=a+b
c

array([[ 6,  8, 10],
       [12, 14, 16]])

#### 3.2 Matrix Subtraction

In [6]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[5,6,7],[8,9,10]])
c=a-b
c

array([[-4, -4, -4],
       [-4, -4, -4]])

#### 3.3 Matrix Multiplication (Hadamard Product)

In [7]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[5,6,7],[8,9,10]])
c=a*b
c

array([[ 5, 12, 21],
       [32, 45, 60]])

#### 3.3 Matrix Division

In [8]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[5,6,7],[8,9,10]])
c=a/b
c

array([[0.2       , 0.33333333, 0.42857143],
       [0.5       , 0.55555556, 0.6       ]])

### 4. Matrix-Matrix Multiplication

In [10]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[6,7,8],[9,10,11],[12,13,14]])
a.dot(b)

array([[ 60,  66,  72],
       [141, 156, 171]])

In [11]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[6,7,8],[9,10,11],[12,13,14]])
a@b

array([[ 60,  66,  72],
       [141, 156, 171]])

### 5. Matrix-Vector Multiplication
A matrix and a vector can be multiplied together as long as the rule of matrix multiplication
is observed. Specifically, that the number of columns in the matrix must equal the number of
items in the vector. 

In [12]:
#matrix
a=np.array([[1,2,3],[4,5,6]])
#vector
b=np.array([1,2,3])
a.dot(b)

array([14, 32])

### 6. Matrix-Scalar Multiplication
A matrix can be multiplied by a scalar. This can be represented using the dot notation between
the matrix and the scalar.

In [15]:
#matrix
a=np.array([[1,2,3],[4,5,6]])
#scalar
b=7
a*b

array([[ 7, 14, 21],
       [28, 35, 42]])