## Numpy Array Basics Operations

In [34]:
from numpy import array

In [35]:
#create array
li=[1.0,2.0,3.0]
ar=array(li)
print(ar)
print(ar.shape)
print(ar.dtype)

[1. 2. 3.]
(3,)
float64


### Empty function to create array , it puts random values

In [36]:
from numpy import empty
#it assign random values
a=empty([3,3])
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### Zero function to create array 

In [37]:
from numpy import zeros
a=zeros([3,5])
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### Ones function to create array 

In [38]:
#Create one array
from numpy import ones
a=ones([3,5])
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


### Combining Arrays
#### 1. Vertical Stack
#### 2. Horizontal Stack

### 1.Vertical Stack

In [39]:
from numpy import array
from numpy import vstack

a1=array([1,2,3])
print(a1)
print(a1.shape)
print()

a2=array([4,5,6])
print(a2)
print(a2.shape)
print()

#vertical stack
a3=vstack((a1,a2))
print(a3)
print(a3.shape)

[1 2 3]
(3,)

[4 5 6]
(3,)

[[1 2 3]
 [4 5 6]]
(2, 3)


### 2.Horizontal Stack

In [40]:
from numpy import array
from numpy import hstack

a1=array([1,2,3])
print(a1)
print(a1.shape)
print()

a2=array([4,5,6])
print(a2)
print(a2.shape)
print()

#vertical stack
a3=hstack((a1,a2))
print(a3)
print(a3.shape)

[1 2 3]
(3,)

[4 5 6]
(3,)

[1 2 3 4 5 6]
(6,)
