Square, symmetric, triangular, and diagonal matrices that are much as their names suggest.

Identity matrices that are all zero values except along the main diagonal where the values
are 1.

Orthogonal matrices that generalize the idea of perpendicular vectors and have useful
computational properties.

## This tutorial is divided into 6 parts to cover the main types of matrices; they are:
1. Square Matrix

2. Symmetric Matrix

3. Triangular Matrix

4. Diagonal Matrix

5. Identity Matrix

6. Orthogonal Matrix

NumPy provides functions to calculate a triangular matrix from an existing square matrix.
The tril() function to calculate the lower triangular matrix from a given matrix and the
triu() to calculate the upper triangular matrix from a given matrix The example below defines
a 3 × 3 square matrix and calculates the lower and upper triangular matrix from it.

In [4]:
import numpy as np
a=np.array([1,2,3])
np.triu(a)

array([[1, 2, 3],
       [0, 2, 3],
       [0, 0, 3]])

In [6]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
np.triu(a)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [7]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
np.tril(a)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [9]:
di=np.diag(a)
di

array([1, 5, 9])