A vector is a tuple of one or more values called scalars.

Vectors are built from components, which are ordinary numbers. You can think of
a vector as a list of numbers, and vector algebra as operations performed on the
numbers in the list.

### 1.1 Defining a vector

In [11]:
import numpy as np
a=np.array([1,2,3])
a

array([1, 2, 3])

### 1.2 Vector Arithmetic

### 1.2.1 Vector Addition

In [12]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=a+b
c

array([5, 7, 9])

### 1.2.2 Vector Subtraction

In [13]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=a-b
c

array([-3, -3, -3])

### 1.2.3 Vector Multiplication

In [14]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=a*b
c

array([ 4, 10, 18])

### 1.2.4 Vector Division

In [15]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=a/b
c

array([0.25, 0.4 , 0.5 ])

### 1.2.5 Vector Dot Product

We can calculate the sum of the multiplied elements of two vectors of the same length to give a
scalar. 

In [16]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=a.dot(b)
c

32

### 1.2.6 Vector-Scalar Multiplication

In [17]:
a=np.array([1,2,3])
c=5*a
c

array([ 5, 10, 15])